const d = new Date()
const pad = n => String(n).padStart(2,'0')
const gmt7 = new Date(d.getTime() + 7 * 3600 * 1000)
const ours = gmt7.toISOString().replace(/[-T:.Z]/g, '').slice(0, 14)
const vn = new Date(d.toLocaleString('en-US', {timeZone: 'Asia/Ho_Chi_Minh'}))
const demo = vn.getFullYear()+pad(vn.getMonth()+1)+pad(vn.getDate())+pad(vn.getHours())+pad(vn.getMinutes())+pad(vn.getSeconds())
console.log('Our fmtDate:', ours)
console.log('Demo fmtDate:', demo)
console.log('Match:', ours === demo)
